# Generated by Django 4.0.1 on 2022-04-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='hide_info',
            field=models.BooleanField(default=False),
        ),
    ]
