# Generated by Django 4.0.1 on 2022-04-17 23:37

from django.db import migrations, models
import public_chat.models


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicchatroom',
            name='about',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='publicchatroom',
            name='profile_image',
            field=models.ImageField(blank=True, default=public_chat.models.get_default_group_image, max_length=255, null=True, upload_to=public_chat.models.get_group_image_filepath),
        ),
    ]
