# Generated by Django 4.0.1 on 2022-03-16 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0002_alter_publicchatroom_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicchatroom',
            options={'verbose_name': 'Room'},
        ),
        migrations.AlterModelOptions(
            name='publicroomchatmessage',
            options={'verbose_name': 'message'},
        ),
    ]
