# Generated by Django 4.0.1 on 2022-04-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_chat', '0002_publicchatroom_about_publicchatroom_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicchatroom',
            old_name='profile_image',
            new_name='group_image',
        ),
    ]
