# Generated by Django 4.0.1 on 2022-03-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='redirect_url',
            field=models.URLField(blank=True, help_text='The URL to be visited when a notification is clicked.', max_length=500, null=True),
        ),
    ]
