# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRemoveAFriend():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_removeAFriend(self):
    # Test name: Remove A Friend
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:8000/ | 
    self.driver.get("http://127.0.0.1:8000/")
    # 2 | setWindowSize | 1283x918 | 
    self.driver.set_window_size(1283, 918)
    # 3 | click | id=id_profile_links | 
    self.driver.find_element(By.ID, "id_profile_links").click()
    # 4 | click | linkText=Account | 
    self.driver.find_element(By.LINK_TEXT, "Account").click()
    # 5 | click | css=.friend-text | 
    self.driver.find_element(By.CSS_SELECTOR, ".friend-text").click()
    # 6 | click | css=.d-flex:nth-child(2) .card-title | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(2) .card-title").click()
    # 7 | click | id=id_friends_toggle | 
    self.driver.find_element(By.ID, "id_friends_toggle").click()
    # 8 | click | linkText=Unfriend | 
    self.driver.find_element(By.LINK_TEXT, "Unfriend").click()
    # 9 | assertText | id=id_send_friend_request_btn | Send Friend Request
    assert self.driver.find_element(By.ID, "id_send_friend_request_btn").text == "Send Friend Request"
    # 10 | close |  | 
    self.driver.close()
  
