# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeclineFriendRequest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_declineFriendRequest(self):
    # Test name: Decline Friend Request
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:8000/account/2/ | 
    self.driver.get("http://127.0.0.1:8000/account/2/")
    # 2 | click | css=.card:nth-child(2) .friend-text | 
    self.driver.find_element(By.CSS_SELECTOR, ".card:nth-child(2) .friend-text").click()
    # 3 | click | id=id_cancel_1 | 
    self.driver.find_element(By.ID, "id_cancel_1").click()
    # 4 | close |  | 
    self.driver.close()
  
