# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSendingAMessage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sendingAMessage(self):
    # Test name: Sending A Message
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://127.0.0.1:8000//")
    # 2 | click | css=#id_chat_notification_dropdown_toggle > .d-flex | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_chat_notification_dropdown_toggle > .d-flex").click()
    # 3 | click | css=.mr-2:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".mr-2:nth-child(1)").click()
    # 4 | click | id=id_chat_message_input | 
    self.driver.find_element(By.ID, "id_chat_message_input").click()
    # 5 | type | id=id_chat_message_input | Hi
    self.driver.find_element(By.ID, "id_chat_message_input").send_keys("Hi")
    # 6 | click | id=id_chat_message_submit | 
    self.driver.find_element(By.ID, "id_chat_message_submit").click()
    # 7 | mouseOver | id=id_chat_message_submit | 
    element = self.driver.find_element(By.ID, "id_chat_message_submit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | mouseOut | id=id_chat_message_submit | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 9 | click | css=.d-flex:nth-child(1) > .d-flex > .msg-p > p | 
    self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .d-flex > .msg-p > p").click()
    # 10 | assertText | css=.d-flex:nth-child(1) > .d-flex > .msg-p > p | Hi
    assert self.driver.find_element(By.CSS_SELECTOR, ".d-flex:nth-child(1) > .d-flex > .msg-p > p").text == "Hi"
  
