# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSendingAFriendRequest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sendingAFriendRequest(self):
    # Test name: Sending A Friend Request
    # Step # | name | target | value
    # 1 | open | http://127.0.0.1:8000/account/2/ | 
    self.driver.get("http://127.0.0.1:8000/account/2/")
    # 2 | click | id=id_send_friend_request_btn | 
    self.driver.find_element(By.ID, "id_send_friend_request_btn").click()
    # 3 | assertText | id=id_cancel_friend_request_btn | Cancel Friend Request
    assert self.driver.find_element(By.ID, "id_cancel_friend_request_btn").text == "Cancel Friend Request"
  
