# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSendingAnEmptyMessage():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_sendingAnEmptyMessage(self):
    # Test name: Sending An Empty Message
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://127.0.0.1:8000//")
    # 2 | click | css=#id_chat_notification_dropdown_toggle > .d-flex | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_chat_notification_dropdown_toggle > .d-flex").click()
    # 3 | click | css=.chat-dropdown-header | 
    self.driver.find_element(By.CSS_SELECTOR, ".chat-dropdown-header").click()
    # 4 | click | id=id_chat_message_input | 
    self.driver.find_element(By.ID, "id_chat_message_input").click()
    # 5 | click | id=id_chat_message_submit | 
    self.driver.find_element(By.ID, "id_chat_message_submit").click()
    # 6 | mouseOver | id=id_chat_message_submit | 
    element = self.driver.find_element(By.ID, "id_chat_message_submit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 7 | mouseOut | id=id_chat_message_submit | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 8 | click | id=id_client_error_modal_body | 
    self.driver.find_element(By.ID, "id_client_error_modal_body").click()
    # 9 | assertText | id=id_client_error_modal_body | You can't send an empty message.
    assert self.driver.find_element(By.ID, "id_client_error_modal_body").text == "You can\\\'t send an empty message."
  
