# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSelectinganUnfriendedUser():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_selectinganUnfriendedUser(self):
    # Test name: Selecting an Unfriended User
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("http://127.0.0.1:8000//")
    # 2 | click | css=#id_chat_notification_dropdown_toggle > .d-flex | 
    self.driver.find_element(By.CSS_SELECTOR, "#id_chat_notification_dropdown_toggle > .d-flex").click()
    # 3 | click | css=.mr-2:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".mr-2:nth-child(1)").click()
    # 4 | click | xpath=//div[@id='id_friend_container_1']/div/span | 
    self.driver.find_element(By.XPATH, "//div[@id=\'id_friend_container_1\']/div/span").click()
    # 5 | mouseOver | css=#id_friend_container_3 .username-span | 
    element = self.driver.find_element(By.CSS_SELECTOR, "#id_friend_container_3 .username-span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 6 | mouseOut | css=#id_friend_container_3 .username-span | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 7 | click | css=.modal-body | 
    self.driver.find_element(By.CSS_SELECTOR, ".modal-body").click()
    # 8 | assertText | id=id_client_error_modal_body | You must be friends to chat.
    assert self.driver.find_element(By.ID, "id_client_error_modal_body").text == "You must be friends to chat."
  
